const URL_ERROR_CODES = Object.freeze({
  INVALID_FORMAT: "INVALID_FORMAT",
  UNSUPPORTED_HOST: "UNSUPPORTED_HOST",
  UNSUPPORTED_ROUTE: "UNSUPPORTED_ROUTE",
  NOT_A_FILE: "NOT_A_FILE",
  UNSUPPORTED_EXTENSION: "UNSUPPORTED_EXTENSION",
});

const SUPPORTED_EXTENSIONS = Object.freeze(["md", "txt", "json", "js", "ts"]);

module.exports = {
  URL_ERROR_CODES,
  SUPPORTED_EXTENSIONS,
};
